INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Luis', 'Lira', 'llira@mticonsultoria.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Ana', 'Ledezma', 'ana@gmail.com', now());
INSERT INTO customers (full_name, last_name, email, created_at) VALUES('Chelsea', 'Lira', 'chelsea@gmail.com', '2020-08-28');