INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2020-01-01', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2020-02-02', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2020-03-03', false);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2020-04-04', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2020-05-05', false);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2020-01-02', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2020-02-03', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2020-03-04', false);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2020-09-10', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2020-08-19', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2020-07-23', false);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2020-09-20', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Luis', 'Lira', 'llira@mticonsultoria.com', '2020-10-01', true);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Ana', 'Ledezma', 'ana@gmail.com', '2020-05-01', false);
INSERT INTO customers (full_name, last_name, email, created_at, active) VALUES('Chelsea', 'Lira', 'chelsea@gmail.com', '2020-08-28', true);